### ISSUE TITLE
Icon error

### ISSUE THREAD

**Issue by mattlanham** [develar/onshape-desktop-shell#1]
Hey, I am trying to learn a little about distributing an app for Windows, and when I run your example, i'm getting the following error:

```
Packaging app for platform win32 x64 using electron v0.37.2
Error: fixme:heap:HeapSetInformation 0x0 1 0x0 0
Fatal error: Unable to set icon
```

I wonder if you knew what was happening here?

**Comment by develar** [comment]
Please install git-lfs — this repo requires it. And after install `git lfs pull`.
