### ISSUE TITLE
Security Certificate expired for windows download

### ISSUE THREAD

**Issue by JimDaly** [develar/onshape-desktop-shell#16]
Attempting to download the windows build at https://onshape-download.develar.org/download, Chrome tells me that:
Your connection is not private

Attackers might be trying to steal your information from onshape-download.develar.org (for example, passwords, messages, or credit cards). NET::ERR_CERT_DATE_INVALID
...
This server could not prove that it is onshape-download.develar.org; its security certificate expired 19 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection....

**Comment by develar** [comment]
Working on cert updating, thanks for issue.
