### ISSUE TITLE
Is your app Sandboxed?

### ISSUE THREAD

**Issue by hp011235** [develar/onshape-desktop-shell#3]
Hi,

How did you sandbox your app by providing the entitlements file? I was not able to find any documentation for the same in electron-builder.

Any help would highly be appreciated.

Thanks,
-Hetal

**Comment by develar** [comment]
@hp011235 It is better to file such issues to electron-builder.

> How did you sandbox your app by providing the entitlements file?

I distribute app using DMG, not AppStore.

By default, `entitlements` is not specified. Only for `mas` target (https://github.com/electron-userland/electron-osx-sign/blob/master/default.mas.entitlements).

Also, you can specify own — `osx-sign` in the [build](https://github.com/electron-userland/electron-builder/wiki/Options#build) (see https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#osx-sign).

**Comment by hp011235** [comment]
I tried providing this under the build in my package.json; but still not working. I am also not sure that every option for electron-packager will work under build.

`"build": {
    "app-bundle-id": "com.abc.xyz",
    "app-category-type": "public.app-category.finance",
    "osx-sign": {
      "identity": "Dev Name",
      "entitlements": "./Provisioning/parent.debug.entitlements"
    }
}`

**Comment by hp011235** [comment]
I was able to resolve this by restarting my machine. I don't know why, but totally weird. Now, it is showing that my app is sandboxed. Thanks for the help. I am getting some other problem, but I will carry that over to the electron-builder thread.
