### ISSUE TITLE
Categories= key missing in onshape.desktop; not showing in menu properly

### ISSUE THREAD

**Issue by probonopd** [develar/onshape-desktop-shell#48]
Currently, the `onshape.desktop` file looks like this:

```
[Desktop Entry]
Name=Onshape
Comment=Onshape desktop app (web application shell)
Exec=AppRun
Terminal=false
Type=Application
Icon=onshape
X-AppImage-Version=0.5.12.355
X-AppImage-BuildId=33733a40-5771-11a7-0985-b16423d82cf2
```

The result is that Onshape will appear under "Lost and found" in the start menu (e.g., in KDE Plasma). There should be at least one main category from https://standards.freedesktop.org/menu-spec/latest/apa.html#main-category-registry set, e.g., `Categories=Graphics;`. Then Onshape would appear correctly in the menu.

This is especially important for the optional `appimaged` daemon which integrates every downloaded AppImage into the menu automatically.

Possibly this is also a feature request for `electron-builder`, to always enforce having at least one main category set. This may become a requirement in the automated review for inclusion in AppImageHub, the upcoming central database of AppImages.

**Comment by develar** [comment]
In the Xubuntu it in the Other category. Changed to suggested category.

**Comment by develar** [comment]
> to always enforce having at least one main category set

Do you know generic category that we can use?

**Comment by probonopd** [comment]
At least one of the main categories needs to be set.
https://standards.freedesktop.org/menu-spec/latest/apa.html

**Comment by develar** [comment]
Default category will be set to `Utility`. And warning printed. Thanks a lot for suggestion.
