### ISSUE TITLE
Version 0.4.4 does not work on Mac OS X El Capitan

### ISSUE THREAD

**Issue by profbrady** [develar/onshape-desktop-shell#5]
When I try to run the Onshape Desktop shell on my Mac I get the following error:

    The application “Onshape” can’t be opened.

**Comment by develar** [comment]
Please try 0.4.5 — https://github.com/develar/onshape-desktop-shell/releases/download/v0.4.5/Onshape-0.4.5.dmg

**Comment by profbrady** [comment]
Still the same error. If I double-click on the icon in the DMG, i get a “verifying” dialog and then it runs. But no matter what I do, when I copy or drag the icon from the DMG to the Applications folder it will not run.

Brian

**Comment by profbrady** [comment]
Strange, I copied the Onshape icon from the DMG to my desktop and it would run. If I moved it to the Applications folder, I get the error. I am just going to keep it on the desktop and run it from there for now.

Brian

**Comment by develar** [comment]
Please try to restart.

**Comment by profbrady** [comment]
Restart did not work. Still running from with the copy installed on my desktop.

Brian

**Comment by develar** [comment]
Strange. Could you please open Console (standard os x app) — what do you see in the log when do you open app from the /Applications?

**Comment by profbrady** [comment]
Very strange indeed. I just removed the copy from Applications and reinstalled it from the DMG (have done this multiple times) and now it starts just fine. Thanks for the quick responses.

Brian
