### ISSUE TITLE
"yarn release" is not a command

### ISSUE THREAD

**Issue by Zamiell** [develar/onshape-desktop-shell#54]
The `.travis.yml` file in this repository is linked from the [official electron-builder documentation](https://www.electron.build/multi-platform-build#docker).

However, I believe this line to be an error:
https://github.com/develar/onshape-desktop-shell/blob/master/.travis.yml#L42

```
root@zamiel-vps:~/asdf# yarn --version
1.3.2
root@zamiel-vps:~/asdf# yarn release
yarn run v1.3.2
error Command "release" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Zamiell** [comment]
Furthermore, it is a separate issue, but please pepper this YAML file with some comments that explain what all of the sections are doing, which order they run in, and so forth. Right now it is completely undocumented.

**Comment by IGassmann** [comment]
@Zamiell You have to add `release` to your `package.json` scripts. See: https://www.electron.build/configuration/publish
