### ISSUE TITLE
Linux Support?

### ISSUE THREAD

**Issue by jamesshawver1** [develar/onshape-desktop-shell#8]
I see that you have both Windows and Mac supported, I personally would love to see Linux supported. I'm currently using Ubuntu, so the debian branches would be great. I could see this really taking off by attaching onshapes comments etc to the desktops notification services etc. :)

**Comment by develar** [comment]
Linux is supported, please use `AppImage` file — latest is https://github.com/develar/onshape-desktop-shell/releases/download/v0.5.1/Onshape-0.5.1.AppImage (make file executable to run it).

>  I could see this really taking off by attaching onshapes comments etc to the desktops notification services etc.

If I understand correctly, it is not yet supported. Feel free to open new issue about it.,

**Comment by jamesshawver1** [comment]
ok. thanks!
